version: '3.3'

services:

  strategy-heartbeat:
    image: sammlerio/strategy-heartbeat
    container_name: strategy-heartbeat
    environment:
      - NODE_ENV=production
      - PORT=3101
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammlerio
      - ENABLE_AUDIT_LOG=true
    ports:
      - "3101:3101"
    depends_on:
      - mongo
      - nats-streaming

    # --------------------------------------
    #            Infrastructure
    # --------------------------------------
    mongo:
      image: mongo
      container_name: mongo
      ports:
      - "27017:27017"
      logging:
        driver: none

    nats-streaming:
      image: nats-streaming
      ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
      - "8222:8222"
      volumes:
      - ./.datastore:/datastore
      command: [
        "-m", "8222",
        "--store", "FILE",
        "--dir", "datastore"
      ]
