ARG NODE_VER="10.13.0"

FROM node:${NODE_VER}-alpine as RELEASE

ENV HOME_DIR "opt/strategy-heartbeat"
RUN mkdir -p $HOME_DIR
WORKDIR $HOME_DIR

COPY index.js package.json ./

RUN npm config set loglevel warn
RUN npm install --quiet --only=production --no-package-lock

COPY /src ./src/

ARG PORT=3101
ENV port=${PORT}
EXPOSE $port

CMD ["npm", "run", "start"]
