version: '3.3'

services:

  # --------------------------------------
  #              Infrastructure
  # --------------------------------------
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"
    logging:
      driver: none

  nats-streaming:
    image: nats-streaming
    ports:
    - "4222:4222"
    - "4223:4223"
    - "8223:8223"
    - "8222:8222"
    volumes:
    - ./.datastore:/datastore
    command: [
      "-m", "8222",
      "--store", "FILE",
      "--dir", "datastore"
    ]

  natsboard:
    image: urashidmalik/natsboard
    ports:
      - "4000:3000"
      - "4001:3001"
    environment:
      - NATS_MONITOR_URL=http://nats-streaming:8222

  # --------------------------------------
  #                Services
  # --------------------------------------


