version: '3.3'

services:

  strategy-heartbeat:
    image: sammlerio/strategy-heartbeat
    container_name: strategy-heartbeat
    environment:
      - NODE_ENV=production
      - SERVICE_NAME=strategy-heartbeat
      - LOG_SERVICE_URI=http://log-service:3004
    volumes:
      - ./src:/opt/strategy-heartbeat
