version: '3.3'
services:

  # --------------------------------------
  #            Infrastructure
  # --------------------------------------
  mongo:
    image: sammlerio/mongo
    container_name: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none

  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "4223:4223"
      - "8223:8223"
      - "8222:8222"
    volumes:
      - ./.datastore:/datastore
    command: [
      "-m", "8222",
      "--store", "FILE",
      "--dir", "datastore"
    ]

  natsboard:
    image: urashidmalik/natsboard
    ports:
      - "4000:3000"
      - "4001:3001"
    environment:
      - NATS_MONITOR_URL=http://nats-streaming:8222

  # --------------------------------------
  #                 Seed
  # --------------------------------------
  mongo-seed:
    image: stefanwalther/mongo-seed
    container_name: mongo-seed
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./config/db-seed:/data
    command: [
      "mongoimport --host mongo --port 27017 --db db --mode upsert --type json --file /data/auth-service~~user.json --jsonArray"
    ]
  # --------------------------------------
  #                Services
  # --------------------------------------

  jobs-service:
    container_name: jobs-service
    image: sammlerio/jobs-service
    environment:
      - NODE_ENV=dev
      - PORT=3003
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=db
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
      - ENABLE_AUDIT_LOG=true
    ports:
      - "3003:3003"
    command: ["npm", "run", "start"]
    depends_on:
      - mongo
      - nats-streaming

  strategy-heartbeat:
    container_name: strategy-heartbeat
    image: sammlerio/strategy-heartbeat
    environment:
      - NODE_ENV=development
      - PORT=3101
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=db
      - ENABLE_AUDIT_LOG=false
      - JOBS_SERVICE_URI=http://jobs-service:3003
    ports:
      - "3101:3101"
    volumes:
      - ./coverage:/coverage
      - ./:/opt/strategy-heartbeat
    command: ["npm", "run", "start:watch"]
    depends_on:
      - mongo
      - nats-streaming

  auth-service:
    image: sammlerio/auth-service
    container_name: auth-service
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=db
      - NATS_STREAMING_HOST=nats-streaming
      - NATS_STREAMING_PORT=4222
      - ENABLE_AUDIT_LOG=true
    depends_on:
      - mongo
      - nats-streaming
