version: '3.3'

services:

  nats-streaming:
    image: nats-streaming
    ports:
    - "4222:4222"
    - "4223:4223"
    - "8223:8223"
    - "8222:8222"
    volumes:
    - ./.datastore:/datastore
    command: [
      "-m", "8222",
      "--store", "FILE",
      "--dir", "datastore"
    ]

  natsboard:
    image: urashidmalik/natsboard
    ports:
      - "4000:3000"
      - "4001:3001"
    environment:
      - NATS_MONITOR_URL=http://nats-streaming:8222

  scheduler:
    image: "sammlerio/scheduler"
    container_name: scheduler
    environment:
      - LOAD_JOBS_FROM_FILE=true
      - NATS_URI=nats://nats-streaming:4222
    ports:
      - "3001:3001"
    volumes:
      - ./config/scheduler/jobs/jobs.yml:/opt/scheduler/src/config/jobs-seeds/jobs.yml
    command: ["npm", "run", "start"]


