jobs:
  - name: heartbeat_every_minute
    enabled: true
    strategy: cron
    cron:
      def: "* * * * *"
    nats:
      subject: HeartbeatRequest
      data:
        name: heartbeat_every_minute_x
